In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
type(mylist)

list

In [6]:
 arr = np.array(mylist)

In [7]:
arr

array([1, 2, 3])

In [8]:
type(arr)

numpy.ndarray

In [9]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
mymatrix = np.array(mylist)

In [11]:
mymatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
mymatrix.shape

(3, 3)

In [13]:
mynewmatrix = np.array(mylist)

In [14]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
type(0.0)

float

In [17]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.ones((5,5)) +4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [20]:
np.ones(4)*100

array([100., 100., 100., 100.])

In [21]:
np.ones(4)/100

array([0.01, 0.01, 0.01, 0.01])

In [22]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [23]:
len(np.linspace(0,10,20))

20

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.random.rand(1)

array([0.92641856])

In [26]:
np.random.rand(4)

array([0.04754888, 0.92264469, 0.82953081, 0.40247549])

In [27]:
np.random.rand(5,5) ## This numbers are distributed normally.
                    # showing normal distribuiton here

array([[0.55503655, 0.24106559, 0.95205607, 0.79625003, 0.05674715],
       [0.04407471, 0.85978716, 0.8778129 , 0.59327815, 0.69837723],
       [0.48808136, 0.14171949, 0.49105844, 0.58496479, 0.5679462 ],
       [0.66366864, 0.46816658, 0.61302225, 0.92156412, 0.08424046],
       [0.7900688 , 0.05962493, 0.64959343, 0.98819741, 0.11726498]])

# Standard normal distribution has mean of 0 and standard deviation of 1

In [28]:
np.random.randn(1)

array([1.75201212])

In [29]:
np.random.randn(4,4) ## randn --> returns numbers according to std deviation

array([[-0.87606146, -0.76326614,  0.4430177 ,  0.25177064],
       [-0.91962705, -1.95301619, -0.29469334,  2.68276471],
       [-0.25910609, -1.33564094, -1.91417024,  0.94987891],
       [ 0.04417558, -0.13066591,  0.09738056, -0.29258564]])

In [30]:
np.random.randn(10)

array([ 1.90387854,  1.30857213, -0.83846969,  0.87629757,  1.48648883,
       -0.78946994,  1.27625307,  0.54728829,  0.8259607 ,  1.2377107 ])

In [31]:
np.random.normal(loc=0,scale=1,size=(5,5)) # loc is mean,scale is std deviation

array([[ 0.86087699, -0.05299528,  0.27404404, -0.67255913, -0.39082648],
       [-0.2012077 , -0.60144558,  1.65471193, -0.11277802,  0.48232536],
       [ 1.1102898 ,  2.40560417, -0.36556573,  1.60377902,  0.47475287],
       [-0.44810442,  0.06155392,  0.29903625,  0.19843305,  1.4931255 ],
       [-0.07773294, -0.5732833 , -0.31437258, -0.33021084,  2.12687073]])

In [32]:
np.random.randint(1,100,10)

array([38, 18, 16, 32, 12, 80, 56, 32, 45, 42])

In [33]:
## array attributes and methods
arr = np.arange(25)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
ranarr = np.random.randint(0,50,10)

In [36]:
ranarr

array([13, 40, 28, 48, 44, 45, 29, 43,  2,  5])

In [37]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
## max min argmax argmin

ranarr.max()

48

In [39]:
ranarr.min()

2

In [40]:
ranarr

array([13, 40, 28, 48, 44, 45, 29, 43,  2,  5])

In [41]:
ranarr.argmax() ## returns the index of max number

3

In [42]:
ranarr.argmin() # returns the index of min number

8

In [43]:
ranarr.dtype

dtype('int32')

# Numpy Indexing and selction

In [44]:
arr = np.arange(0,11)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr[8]

8

In [47]:
arr[1:] #  from index 1 onwards

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr[1:5] # from index 1 till 4.. python exclude upper bound

array([1, 2, 3, 4])

In [49]:
arr[:5] # from start till the 5 but exclude last one

array([0, 1, 2, 3, 4])

# broadcasting

In [50]:
arr +100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [51]:
new_arr = arr/2

In [52]:
new_arr

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [55]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
slic_of_arr = arr[0:6]

In [57]:
slic_of_arr

array([0, 1, 2, 3, 4, 5])

In [58]:
slic_of_arr[:] = 99

In [59]:
slic_of_arr

array([99, 99, 99, 99, 99, 99])

In [60]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [61]:
arr_copy = arr.copy()

In [62]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [63]:
arr_copy [:] =1000

In [64]:
arr_copy

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [65]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# INdexing of two dimentional array

In [66]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [67]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [68]:
arr_2d.shape

(3, 3)

In [69]:
arr_2d[1,1]

25

In [70]:
arr_2d[2,2]

45

In [71]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [72]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [73]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [74]:
arr = np.arange(1,11)

In [75]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [77]:
bool_arr = arr >4

In [78]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [79]:
arr[bool_arr] ## returning the index of the boolean

array([ 5,  6,  7,  8,  9, 10])

In [80]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [81]:
arr[arr ==2]

array([2])

In [82]:
arr[arr<=6]

array([1, 2, 3, 4, 5, 6])

In [83]:
arr = np.arange(0,10)

In [84]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
arr +10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [86]:
arr /100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09])

In [87]:
arr **2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [88]:
(arr+2)/100

array([0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11])

In [89]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [91]:
1/arr

<ipython-input-91-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [92]:
arr/arr

<ipython-input-92-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [94]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [95]:
np.log(arr)

<ipython-input-95-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [96]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [97]:
arr.sum()

45

In [98]:
arr.mean()

4.5

In [99]:
arr.max()

9

In [101]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[10,11,12,13]])

In [102]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [103]:
arr_2d.sum()

82

In [104]:
arr_2d.shape

(3, 4)

In [105]:
arr_2d.sum(axis = 0) ## Sum across the rows

array([16, 19, 22, 25])

In [106]:
 arr_2d.sum(axis =1) ## Sum across columns

array([10, 26, 46])

# Exercise

1. create an array of 10 zeros

In [107]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [109]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

3. create an array of 10 fives

In [110]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

4.create an array of integers from 10 to 50

In [111]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

5.create an array of all even integers from 10 to 50

In [112]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

6.create a 3x3 matrix with values ranging from 0 to 8

In [114]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7. create 3x3 identity matrix

In [115]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

8. Use numpy to generate a random number between 0 and 1

In [116]:
np.random.rand(1)

array([0.43552278])

9. use numpy to generate 25 random numbers sampled from standard normal distribution

In [117]:
np.random.randn(25)

array([ 1.99683781, -1.47989583,  0.38324362,  1.71365803, -1.21083984,
       -0.84483847,  0.82963479, -0.19432674,  1.62585132, -0.0621963 ,
       -0.09235181, -0.24713412,  1.192163  ,  0.14946893, -1.81457329,
       -1.24611571, -0.73925201, -0.59548734,  0.1649112 ,  0.09414191,
       -0.9407501 , -1.66491566,  0.47871143,  0.93757229, -0.75781547])

10. create a matirx

In [120]:
arr = np.arange(1,101)/100
arr.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

11. create  array of 20 linearly space points between 0 and 1 :

In [121]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# Numpy Indexing and solutions

In [122]:
mat = np.arange(1,26).reshape(5,5)

In [127]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

12. write a code to reproduce output given below

In [125]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

13.write a code that gives 20 from above matrix 

In [126]:
 mat[3,4]

20

In [129]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [130]:
mat[:3,1]

array([ 2,  7, 12])

14. return the last row from the matrix

In [131]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [132]:
mat[4]

array([21, 22, 23, 24, 25])

15. write a code that gives last 2 rows

In [133]:
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# Numpy Operations

16. Get th sum of all values in mat

In [134]:
mat.sum()

325

17. get standard deviation of the values in mat

In [135]:
mat.std()

7.211102550927978

18. Get sum of all columns from mat

In [137]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [138]:
np.random.seed(101)
np.random.rand(1)

array([0.51639863])